/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.1. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module blinky
    ( // Inputs
      input wire  BTN


      // Outputs
    , output wire  LED
    );


  assign LED = ~ BTN;


endmodule

